# Workflow to create a github issue every month to facilitate comment based releases
name: Monthly Release Thread

on:
  schedule:
   - cron: 0 0 1 * *  # Every 1st day of the month at 0000 – https://crontab.guru

jobs:
  monthly_release:
    runs-on: ubuntu-latest
    steps:

# Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v4

# Get current month for issue title
    - name: get-date
      id: date
      run: echo "date=$(date +'%B %Y')" >> $GITHUB_OUTPUT

# Create, pin, label, and assign release issue
    - name: create-issue
      id: extract
      uses: imjohnbo/extract-issue-template-fields@v1
      with:
        path: ".github/RELEASE_TEMPLATE.md"

    - name: create-issue
      id: issue
      uses: imjohnbo/issue-bot@v3
      with:
        pinned: true
        close-previous: true
        title: "RELEASE THREAD: ${{ steps.date.outputs.date }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
